# Generated by Django 5.1.4 on 2024-12-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Registered Date')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Update Date')),
            ],
            options={
                'verbose_name': 'BookModel',
                'verbose_name_plural': 'BookModels',
                'ordering': ['-id'],
            },
        ),
    ]
